version: "3"
services:
  appsonair-graphql-server-dev:
    image: shreegopal/nginx:dev
    container_name: appsonair-graphql-server-dev
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appsonair-dev-server.rule=Host(`server.dev.xyz.com`)"
      - "traefik.http.services.appsonair-dev-server.loadbalancer.server.port=3005"
      - "traefik.http.routers.appsonair-dev-server.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.appsonair-dev-server.tls=true"
    env_file:
      - .env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 
        tag: 
        fluentd-async-connect: "true"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true