version: '3'

services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_data/traefik.toml:/traefik.toml
      - ./traefik_data/acme.json:/acme.json
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true